server:
  error:
    include-message: always
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: us-east-2
      dynamodb:
        endpoint: https://dynamodb.us-east-2.amazonaws.com/
        region: us-east-2
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
amazon:
  s3:
    bucket: ${AWS_S3_BUCKET}
  aws:
    accesskey: ${AWS_ACCESS_KEY}
    secretkey: ${AWS_SECRET_KEY}
    region: us-east-2
logging:
  pattern:
    file: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: INFO